title: EmeraldSys Status
name: emeraldsys_status
description: "EmeraldSys Status Dashboard"
defaultLocale: en
baseUrl: "https://status.emeraldsys.xyz"
locales:
  - code: en
    iso: en-US
    name: English
    file: en.json
content:
  frontMatterFormat: json
  systems:
  - pki-api
  - pki-cdn
  - cdn
  - acidityv3-landing
  - acidityv3-api
  - nhlv-frontend
  - nhlv-api
  - nhlv-media-api
  - rbxexchange-frontend
  - rbxexchange-api
  - vpn-oregon