name: "Deploy Statusfy"
on:
  push:
    branches: ["main"]

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Static Site
        run: |
          npm i
          npm run generate
      - name: Publish Static Site
        uses: jamesives/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist